### ISSUE TITLE
Add Installation instructions and description.

### ISSUE THREAD

**Issue by ph4ni** [hannobraun/Fornjot#878]
Hi!

Just thought it would be helpful if you added installation instructions in the readme and a little description in the about section of the repository.

Thanks!

**Comment by hannobraun** [comment]
Hey, @ph4ni, thank you for opening this issue! Documentation is indeed a weak point right now. I'm really busy focusing on core CAD features, so I haven't gotten to it yet.

> and a little description in the about section of the repository.

What kind of description would you like to see there? I kinda like the current one, as it's short and a bit of a teaser. People that agree that the world needs another CAD program can check out the README and website, while those that don't agree don't need to bother :smile: 

I'm closing this issue, since this is already tracked in #55.
